### ISSUE TITLE
Some a11y problems with text color contrast

### ISSUE THREAD

**Issue by RinatValiullov** [matthewp/corset-site#18]
Pretty low text color contrast. Because of what it is very difficult to perceive information.
This is what page looks like on my system (Google Chrome 99.0.4844.51, Windows 10):

![image](https://user-images.githubusercontent.com/9755333/157937373-172ef5bb-665d-4984-bd88-57c98af69aa7.png)

![image](https://user-images.githubusercontent.com/9755333/157937938-91ab28da-a83e-4c8e-8c66-8de216b92367.png)

**Comment by RinatValiullov** [comment]
fixed 

https://github.com/matthewp/corset-site/commit/84ce2bd3af55dc9c4325fc78b3900cc2f5cfe04a

**Comment by matthewp** [comment]
Thanks! I'd you have any other a11y issues I welcome them.
